on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Cache binpkgs
        uses: actions/cache@v2
        with:
          key: key3
          path: binpkgs
      - name: Build ebuilds
        uses: ./.github/actions/gentoo
        with:
          ebuild-names: --usepkg dev-ada/ada-pretty
      - name: Debug output
        run: |
          echo GITHUB_WORKSPACE=$GITHUB_WORKSPACE
          ls -lR $GITHUB_WORKSPACE/binpkgs
