on: [push]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Cache binpkgs
        uses: actions/cache@v2
        with:
          path: ~/binpkgs
          key: key1
      - name: Build ebuilds
        uses: ./.github/actions/gentoo
        with:
          ebuild-names: dev-ada/matreshka
